name: Lab 9 CI Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start containers
        run: docker compose up -d --build

      - name: Install Dependencies
        run: docker exec lab9_php composer install

      - name: Run Tests
        run: docker exec lab9_php ./vendor/bin/phpunit tests

      - name: Stop containers
        if: always()
        run: docker compose down